# Generated by Django 3.0.5 on 2024-02-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='notesdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='User_Notes')),
                ('description', models.TextField()),
            ],
        ),
    ]
